name: "Reviewpad Action"
description: "Reviewpad Action automates pull requests workflows using the Reviewpad configuration language."
branding:
  icon: "send"
  color: "blue"
inputs:
  event:
    description: "GitHub action event"
    default: ${{ toJSON(github) }}
    required: false
  token:
    description: >
      Personal access token (PAT) used to fetch information from the repository. 
      The PAT is configured with the local git config, which enables your scripts 
      to run authenticated git commands. The post-job step removes the PAT.
      We recommend using a service account with the least permissions necessary.
    default: ${{ github.token }}
    required: false
runs:
  using: "docker"
  image: "docker://reviewpad/action:171c75118f53166f8988f85debbeea793d9d99b8"
